### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by vebbo2** [Barteco/Redcache#1]
- [x] Framework multitargeting
- [ ] Docs on classes
- [x] Readme usage
- [ ] Strongly typed keys
- [ ] Extend list APIs
- [ ] Graph API (?)
- [x] Absolute/sliding expiration
- [x] Sample project with usage and logging configured
- [ ] In memory implementation
